name: FeatherQueenOfTheHill
version: '${project.version}'
main: com.zerek.featherqueenofthehill.FeatherQueenOfTheHill
api-version: 1.19
authors: [ Zerek ]
description: PvP Queen(King) of the hill mini-game
commands:
  queen:
    description: used to reload the plugin
    usage:
      /queen <option>
