name: FeatherQueenOfTheHill
version: '${project.version}'
main: dev.zerek.featherqueenofthehill.FeatherQueenOfTheHill
api-version: 1.19
authors: [ Zerek ]
description: PvP Queen(King) of the hill mini-game
commands:
  queen:
    description: Queen Of The Hill command
    usage:
      /queen <option>
